#!/bin/bash
# Remove the ._tmp files generated by aptana studio

source ./config.sh

cd ${SAKAI3_UX}

# Get all the files that have an extension with the following format: tmp_
SAKAI3_UX_TEMP_FILES=`find . -name ".tmp_*"`

# Remove all those files
for i in $SAKAI3_UX_TEMP_FILES
do
    echo "removing $i"
    rm $i
done